version: "3"

services:
  base: &base
    build: .

  test: 
    <<: *base
    command: "test"

  zero_shot:
    <<: *base
    container_name: zero_shot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health_check"]
      interval: 5s
      timeout: 30s
      retries: 5
    user: user
    command: "serve"
    ports:
      - 8080:8080
    networks:
      - ai-hero-internal

  zero_shot_mq:
    <<: *base
    container_name: zero_shot_mq
    env_file: 
      - .env
    depends_on:
      - redis
    user: user
    command: "start_mq"
    networks:
      - ai-hero-internal

  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - ai-hero-internal

networks:
  ai-hero-internal:
    external: true
