#!/bin/bash
set -e 

if [ "$#" -eq 0 ] ; 
then
  echo "Entrypoint did not receive a command."
  echo "Should be one of 'serve', 'test', 'start_mq."
  exit 1
fi

echo "Entrypoint received command: $1"
if [ "$1" = "serve" ] 
then
  ./serve
elif [ "$1" = "test" ]  
then
  ./test
elif [ "$1" = "start_mq" ]  
then
  ./start_mq
else
  echo "Entrypoint received invalid command."
  exit 1
fi
